# version: 0.0
# os: linux
# files:
#   - source: docker-compose.yml
#     destination: /home/ec2-user/
#     overwrite: true   # Add this line to overwrite the existing file
#   - source: start_containers.sh
#     destination: /home/ec2-user/
#     overwrite: true   # Add this line to overwrite the existing file
#   # - source: stop_containers.sh
#   #   destination: /home/ec2-user/
#   #   overwrite: true   # Add this line to overwrite the existing file

# hooks:
#   # BeforeInstall:
#   #   - location: stop_containers.sh
#   #     timeout: 300
#   #     runas: root

#   ApplicationStart:
#     - location: start_containers.sh
#       timeout: 300
#       runas: root

version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:REGION:390402554944:task-definition/my_task"
        LoadBalancerInfo:
          - ContainerName: "frontend"
            ContainerPort: 3000
          - ContainerName: "backend"
            ContainerPort: 5000
