version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/mern-app-cicd 

hooks:
  BeforeInstall:
    - location: stop_containers.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: start_containers.sh
      timeout: 300
      runas: ec2-user
