version: 0.2

env:
  variables:
    DOCKER_USERNAME: "vaibhav188" # Your Docker Hub username

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      # Build and push the frontend image
      - cd client/
      - docker build -t vaibhav188/frontend:$CODEBUILD_BUILD_NUMBER .
      - docker tag vaibhav188/frontend:$CODEBUILD_BUILD_NUMBER vaibhav188/frontend:latest
      - docker images
      - docker push vaibhav188/frontend:$CODEBUILD_BUILD_NUMBER
      # - docker push vaibhav188/frontend:latest

      # Build and push the backend image
      - cd ../server/
      - docker build -t vaibhav188/backend:$CODEBUILD_BUILD_NUMBER .
      - docker tag vaibhav188/backend:$CODEBUILD_BUILD_NUMBER vaibhav188/backend:latest
      - docker images
      - docker push vaibhav188/backend:$CODEBUILD_BUILD_NUMBER
      # - docker push vaibhav188/backend:latest

artifacts:
  files:
    - appspec.yml
    - docker-compose.yml
    - start_containers.sh
    - stop_containers.sh
